# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 04:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_travels', to=settings.AUTH_USER_MODEL),
        ),
    ]
